trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
experimentalTernaries: false
printWidth: 80
quoteProps: 'as-needed'
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
